# Generated by Django 4.1.1 on 2022-09-30 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.IntegerField()),
                ('bid', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='auction_item',
            name='price',
        ),
        migrations.AddField(
            model_name='auction_item',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction_item',
            name='cur_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='auction_item',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cmt',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.DeleteModel(
            name='bid',
        ),
        migrations.AddField(
            model_name='info_bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_item'),
        ),
    ]
