# Generated by Django 4.1.1 on 2022-10-05 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_info_bid_remove_auction_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_bid',
            name='who',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
