# Generated by Django 4.1.1 on 2022-10-07 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_info_bid_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_item',
            name='img',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='cmt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.auction_item'),
        ),
        migrations.AlterField(
            model_name='cmt',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='info_bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidset', to='auctions.auction_item'),
        ),
    ]
