# Generated by Django 4.1.1 on 2022-10-10 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_item_img_alter_cmt_item_alter_cmt_posted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_item',
            name='liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
