# Generated by Django 4.1.1 on 2022-10-13 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_item_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt', to='auctions.auction_item'),
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('item', models.ManyToManyField(related_name='classify', to='auctions.auction_item')),
            ],
        ),
    ]
